[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.automation.actions"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["automation", "actions", "ballerina", "integration", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.automation.actions"

[build-options]
observabilityIncluded = true
